=== Kevin-2-3/ordinario-ftw/recursos/carritoCompras.dtd
<!ELEMENT carritoCompras (producto+)>

<!ELEMENT producto (nombre, cantidad, modelo, precioUnitario, color)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT precioUnitario (#PCDATA)>
<!ELEMENT color (#PCDATA)>

=== Kevin-2-3/ordinario-ftw/recursos/carritoCompras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE carritoCompras SYSTEM "carritoCompras.dtd">
<carritoCompras>
    
    <producto>
        <nombre>Lnyx Lx1</nombre>
        <cantidad>1</cantidad>
        <modelo>LNX-NX2026</modelo>
        <precioUnitario>8499</precioUnitario>
        <color>Azul Estelar</color>
    </producto>

    <producto>
        <nombre>LFold</nombre>
        <cantidad>2</cantidad>
        <modelo>LNX-EP15</modelo>
        <precioUnitario>19998</precioUnitario>
        <color>Plata Plateado</color>
    </producto>

    <producto>
        <nombre>Lnx Start</nombre>
        <cantidad>10</cantidad>
        <modelo>LNX-ASTRT</modelo>
        <precioUnitario>2599</precioUnitario>
        <color>Blanco Nieve</color>
    </producto>

    <producto>
        <nombre>Cable USB-C Reforzado</nombre>
        <cantidad>2</cantidad>
        <modelo>LNX-CUSB4</modelo>
        <precioUnitario>199</precioUnitario>
        <color>Negro-Azul</color>
    </producto>

    <producto>
        <nombre>Cargador Lnyx FastCharge 45W</nombre>
        <cantidad>1</cantidad>
        <modelo>LNX-C45</modelo>
        <precioUnitario>599</precioUnitario>
        <color>Blanco</color>
    </producto>

    <producto>
        <nombre>Audífonos Lnyx SoundPods</nombre>
        <cantidad>2</cantidad>
        <modelo>LNX-SPRO</modelo>
        <precioUnitario>1299</precioUnitario>
        <color>Negro</color>
    </producto>

    <producto>
        <nombre>Power Bank Lnyx 10001 mAh</nombre>
        <cantidad>3</cantidad>
        <modelo>LNX-PWB1</modelo>
        <precioUnitario>599</precioUnitario>
        <color>Azul</color>
    </producto>

    <producto>
        <nombre>LX2u</nombre>
        <cantidad>1</cantidad>
        <modelo>LNX-NS1S</modelo>
        <precioUnitario>21999</precioUnitario>
        <color>Negro Galaxy</color>
    </producto>

</carritoCompras>
